// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLongURL(ctx context.Context, shortUrl string) (string, error)
	GetURL(ctx context.Context, shortUrl string) (Url, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateShortURL(ctx context.Context, arg UpdateShortURLParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
