// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (Url, error)
	GetLongURL(ctx context.Context, id string) (string, error)
}

var _ Querier = (*Queries)(nil)
